pluginManagement {
    includeBuild('build-logic')
}

rootProject.name = 'suh-logger-parent'

include 'suh-logger-core'
include 'suh-logger-spring'
include 'suh-logger-servlet'
include 'suh-logger-spring-boot-autoconfigure'
include 'suh-logger-spring-boot-starter'
include 'suh-logger-legacy'
include 'suh-logger-bom'
