plugins { id 'suh.java-library' }
description = 'suh-logger JsonCodec for Jackson 2 (Spring Boot 3)'

dependencies {
    api project(':suh-logger-core')
    compileOnly libs.jackson2.databind

    testImplementation libs.jackson2.databind
    testImplementation testFixtures(project(':suh-logger-core'))
}
